# Generated by Django 2.2.12 on 2020-04-07 08:56

import django.core.files.storage
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folderless', '0002_auto_20180418_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='author',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='file',
            name='copyright',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='file',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=easy_thumbnails.fields.ThumbnailerField(storage=django.core.files.storage.FileSystemStorage(), upload_to='files', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='name'),
        ),
    ]
