# Generated by Django 3.2.16 on 2022-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folderless', '0003_auto_20200407_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(blank=True, choices=[], max_length=12, verbose_name='File type'),
        ),
    ]
