# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_testgallery_testgalleryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgalleryentry',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.TestGallery'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='only for checking out raw_id_fields!', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
