# Generated by Django 2.2.12 on 2020-04-07 08:56

from django.db import migrations, models
import django.db.models.deletion
import folderless.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_auto_20180418_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgallery',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='testgalleryentry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='testgalleryentry',
            name='image',
            field=folderless.fields.FolderlessFileField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='folderless.File', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='dummy',
            field=models.CharField(blank=True, max_length=255, verbose_name='dummy'),
        ),
    ]
